"""Export offer recommendation as downloadable Excel (.xlsx) and print-ready HTML."""
from __future__ import annotations

import io
from typing import Optional

import pandas as pd

from .recommend import Recommendation


def to_excel(rec: Recommendation, candidate_name: str = "Candidate") -> bytes:
    """Return an in-memory .xlsx workbook as bytes."""
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        # Summary sheet
        summary = pd.DataFrame(
            {
                "Field": [
                    "Candidate",
                    "Level",
                    "Function",
                    "Location",
                    "Confidence",
                    "",
                    "Base (low)",
                    "Base (target)",
                    "Base (high)",
                    "",
                    "Equity — ownership range",
                    "Equity — grant value (if available)",
                    "",
                    "Sign-on",
                    "",
                    "Internal comparisons",
                    "Peer postings with salary",
                ],
                "Value": [
                    candidate_name,
                    f"{rec.level_code} — {rec.level_name}",
                    rec.function,
                    rec.location,
                    rec.confidence,
                    "",
                    f"${rec.base_low:,}",
                    f"${rec.base_target:,}",
                    f"${rec.base_high:,}",
                    "",
                    f"{rec.equity_pct_low:.2f}% – {rec.equity_pct_high:.2f}%",
                    f"${rec.equity_grant_value:,}" if rec.equity_grant_value else "N/A",
                    "",
                    f"${rec.signon_target:,}",
                    "",
                    str(rec.internal_n),
                    str(rec.market_n),
                ],
            }
        )
        summary.to_excel(writer, sheet_name="Offer Summary", index=False)

        # Reasoning sheet
        reasoning = pd.DataFrame({"Reasoning": rec.reasoning})
        reasoning.to_excel(writer, sheet_name="Reasoning", index=False)

        # Widen columns.
        for ws in writer.sheets.values():
            ws.column_dimensions["A"].width = 35
            ws.column_dimensions["B"].width = 40

    return buf.getvalue()


def to_html(rec: Recommendation, candidate_name: str = "Candidate") -> str:
    """Return a print-ready HTML page for the offer summary (save as .html, open in browser, print to PDF)."""
    eq = (
        f"${rec.equity_grant_value:,} grant value"
        if rec.equity_grant_value
        else f"{rec.equity_pct_low:.2f}% – {rec.equity_pct_high:.2f}% ownership"
    )
    reasoning_items = "\n".join(f"    <li>{r}</li>" for r in rec.reasoning)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Offer Summary — {candidate_name}</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 720px; margin: 40px auto; color: #1a1a1a; }}
  h1 {{ font-size: 22px; margin-bottom: 4px; }}
  .subtitle {{ color: #666; font-size: 14px; margin-bottom: 24px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th, td {{ text-align: left; padding: 8px 12px; border-bottom: 1px solid #e0e0e0; }}
  th {{ background: #f7f7f7; font-weight: 600; width: 40%; }}
  .confidence {{ display: inline-block; padding: 4px 12px; border-radius: 4px; font-weight: 600; font-size: 13px; }}
  .confidence.high {{ background: #d4edda; color: #155724; }}
  .confidence.medium {{ background: #fff3cd; color: #856404; }}
  .confidence.low {{ background: #f8d7da; color: #721c24; }}
  h2 {{ font-size: 16px; margin-top: 28px; }}
  ul {{ padding-left: 20px; }}
  li {{ margin-bottom: 6px; font-size: 14px; line-height: 1.5; }}
  .footer {{ margin-top: 32px; font-size: 12px; color: #999; border-top: 1px solid #e0e0e0; padding-top: 12px; }}
  @media print {{ body {{ margin: 20px; }} }}
</style>
</head>
<body>
<h1>Offer Summary</h1>
<p class="subtitle">{candidate_name} &middot; {rec.level_code} {rec.level_name} &middot; {rec.function} &middot; {rec.location}</p>

<table>
  <tr><th>Base salary (target)</th><td><strong>${rec.base_target:,}</strong></td></tr>
  <tr><th>Base range</th><td>${rec.base_low:,} – ${rec.base_high:,}</td></tr>
  <tr><th>Equity</th><td>{eq}</td></tr>
  <tr><th>Sign-on bonus</th><td>${rec.signon_target:,}</td></tr>
  <tr><th>Data sources</th><td>{rec.internal_n} internal, {rec.market_n} peer postings</td></tr>
</table>

<p><span class="confidence {"high" if "High" in rec.confidence else "medium" if "Medium" in rec.confidence else "low"}">{rec.confidence}</span></p>

<h2>How we got here</h2>
<ul>
{reasoning_items}
</ul>

<div class="footer">
  Generated by Matic Comp Benchmarking Tool. Equity and sign-on figures are
  heuristic guidance, not hard market reads. Review with your compensation
  philosophy before extending an offer.
</div>
</body>
</html>"""
